class Bbox:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def w(self) -> float: ...
    @property
    def h(self) -> float: ...
    def center(self) -> tuple[float, float]: ...

class DomElement:
    @property
    def index(self) -> int: ...
    @property
    def tag(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def attrs(self) -> dict[str, str]: ...
    @property
    def bbox(self) -> Bbox: ...

class DomState:
    @property
    def url(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def viewport(self) -> tuple[int, int, float]: ...
    @property
    def elements(self) -> list[DomElement]: ...
    def to_llm_string(self) -> str: ...
    def __len__(self) -> int: ...

class BrowserSession:
    def __init__(self) -> None: ...
    async def start(self) -> None: ...
    async def navigate(self, url: str) -> None: ...
    async def screenshot(self) -> bytes: ...
    async def current_url(self) -> str: ...
    async def dom_snapshot(self) -> DomState: ...
    async def click_index(self, index: int) -> None: ...
    async def type_index(self, index: int, text: str) -> None: ...
    async def scroll(self, dy: float) -> None: ...
    async def stop(self) -> None: ...

def version() -> str: ...
