class Bbox:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def w(self) -> float: ...
    @property
    def h(self) -> float: ...
    def center(self) -> tuple[float, float]: ...

class DomElement:
    @property
    def index(self) -> int: ...
    @property
    def tag(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def attrs(self) -> dict[str, str]: ...
    @property
    def bbox(self) -> Bbox: ...

class DomState:
    @property
    def url(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def viewport(self) -> tuple[int, int, float]: ...
    @property
    def elements(self) -> list[DomElement]: ...
    def to_llm_string(self) -> str: ...
    def __len__(self) -> int: ...

class BrowserSession:
    def __init__(
        self,
        headless: bool = True,
        viewport: tuple[int, int] | None = (1280, 900),
        chrome_path: str | None = None,
        extra_chrome_args: list[str] | None = None,
        cdp_url: str | None = None,
        allowed_domains: list[str] | None = None,
        prohibited_domains: list[str] | None = None,
        stealth: bool = False,
    ) -> None: ...
    async def start(self) -> None: ...
    async def navigate(self, url: str) -> None: ...
    async def screenshot(self) -> bytes: ...
    async def pdf(self) -> bytes: ...
    async def current_url(self) -> str: ...
    async def dom_snapshot(self) -> DomState: ...
    async def click_index(self, index: int) -> None: ...
    async def type_index(self, index: int, text: str) -> None: ...
    async def upload_file(self, index: int, paths: list[str]) -> None: ...
    async def scroll(self, dy: float) -> None: ...
    async def scroll_to_index(self, index: int) -> None: ...
    async def scroll_to_top(self) -> None: ...
    async def scroll_to_bottom(self) -> None: ...
    async def get_text(self, selector: str) -> str: ...
    async def page_text(self, max_chars: int = 10000) -> str: ...
    async def get_links(self) -> list[tuple[str, str]]: ...
    async def wait_for_navigation(self, timeout_ms: int = 10000) -> bool: ...
    async def wait_for_selector(self, selector: str, timeout_ms: int = 5000) -> bool: ...
    async def list_tabs(self) -> list[tuple[str, str, str, str, bool]]: ...
    async def switch_tab(self, target_id: str) -> None: ...
    async def new_tab(self, url: str = "") -> tuple[str, str, str, str, bool]: ...
    async def close_tab(self, target_id: str) -> None: ...
    async def download_dir(self) -> str: ...
    async def list_downloads(
        self,
    ) -> list[tuple[str, str, str, str, int, int, str]]: ...
    async def get_cookies(
        self,
    ) -> list[tuple[str, str, str, str, float, bool, bool]]: ...
    async def set_cookie(
        self,
        name: str,
        value: str,
        domain: str,
        path: str = "/",
        expires: float = -1.0,
        secure: bool = False,
        http_only: bool = False,
    ) -> None: ...
    async def delete_cookie(
        self,
        name: str,
        domain: str | None = None,
        path: str | None = None,
    ) -> None: ...
    async def clear_cookies(self) -> None: ...
    async def stop(self) -> None: ...
    async def kill(self) -> None: ...

def version() -> str: ...
